name: cicd

on:
  push:
    branches:
      - 'master'

jobs:
  ci:
    uses: dohrniicloud/common-action-modules/.github/workflows/docker.yml@task-2tt986n
    with:
      aws-region: us-east-1
      push-to-ecr: true
      repository: my-repo
    secrets:
      role-to-assume: "arn:aws:iam::912343663134:role/provideEcrAccess"

  check:
    name: checking if the output exists
    runs-on: ubuntu-latest
    needs: ci
    steps:
    - name: check-output
      run:
        echo "${{ needs.ci.outputs.image}}"
#dddddcn






  # cd:
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   needs: ci
  #   steps:
  #   - name: Fill in the new image ID in the Amazon ECS task definition
  #     id: task-def
  #     uses: aws-actions/amazon-ecs-render-task-definition@v1
  #     with:
  #       task-definition: task-definition.json
  #       container-name: my-container
  #       image: ${{ needs.ci.outputs.imageid}}

  #   - name: Deploy Amazon ECS task definition
  #     uses: aws-actions/amazon-ecs-deploy-task-definition@v1
  #     with:
  #       task-definition: ${{ steps.task-def.outputs.task-definition }}
  #       service: my-service
  #       cluster: my-cluster
  #       wait-for-service-stability: true
    

    
