name: ci

on:
  push:
    branches:
      - 'master'
#permissions:
 #     id-token: write
  #    contents: read

jobs:
  docker:

        uses: dohrniicloud/common-action-modules/.github/workflows/docker.yml@task-2tt986n
        with:
          aws-region: us-east-1
          push-to-ecr: true
        secrets:
          role-to-assume: "arn:aws:iam::912343663134:role/provideEcrAccess"

    
