name: ci

on:
  push:
    branches:
      - 'master'
permissions:
      id-token: write
      contents: read

jobs:
  docker:

        uses: dohrniicloud/common-action-modules/.github/workflows/docker.yml@task-2tt986n
        with:
          push-to-ghcr: true
          repository: "github_actions"
    
